README.md

Can you please confirm I'm right about these edits @johndmulhausen?

Update repo and folder names

---

docs/.vuepress/theme/styles/index.styl

override default table row highlighting

---

docs/.vuepress/theme/styles/index.styl

Does what it says, says what it does.

fix: remove font ligatures

---

docs/.vuepress/config.js
docs/README.md
package-lock.json
package.json

This adds a tab switcher plugin to close #20
I added an example to the index page, since we're using it as a style gallery ATM.

add tab switcher plugin

---

docs/how-tos/store.md

This adds a couple scary boxes to warn that all data is public and you can't really delete things.
I'm happy to tweak the language if anyone has feelings / ideas :)
cc @jnthnvctr

add warnings to storage how-to about deletion and data privacy

---

docs/README.md

Moves _public-data_ warning further up page.

---

docs/.vuepress/theme/styles/tabs.styl
docs/.vuepress/theme/styles/theme-dark.styl

Fixes styling of the new tabs component.

fix: new tabs components styles

---

docs/.vuepress/theme/styles/sidebar.styl

This PR addresses the issue raised by @jnthnvctr of left-nav headers with links not displaying in the same manner as non-link headers — however, it's not very tidy. @zebateira, do you have the bandwidth to have a look? 🙏

Style: update nav so clickable headers match formatting

---

docs/.vuepress/config.js

Update footer link text

---

docs/.vuepress/theme/styles/code-copy.styl
docs/.vuepress/theme/styles/index.styl

https://user-images.githubusercontent.com/2353186/126813737-6e7472f2-9f05-4ca8-a0ad-d7844204af0b.mp4
https://user-images.githubusercontent.com/2353186/126813610-a820f985-6eac-4b05-9375-4ad3718bb80a.mp4
(also removed border-radius from the whole code block to be more inline with the design - let me know if it's not okay to revert)

fix: position code copy button to stick to the right of the container

---

docs/how-tos/retrieve.md

Adds steps for retrieving files using the command-line for Linux, macOS, and Windows.

Adds terminal steps to Retrieve how-to page.

---

docs/.vuepress/config.js

Closes #58 by moving how to section about concepts section. 
@johnnymatthews This is coming out as a white screen for me locally although I don't know what step I would've missed here. Mind taking a look? 
Edit: Working after an NPM install and seems to be fine in preview, so feel free to merge if it's looking okay for you.

update nav order in config

---

README.md

@jessicaschilling mind merging if you don't spot anything if you don't spot anything weird?

Update readme to reflect new URL for docs site

---

docs/.vuepress/theme/components/Page.vue
docs/.vuepress/theme/layouts/GlobalLayout.vue
docs/.vuepress/theme/styles/index.styl
docs/.vuepress/theme/styles/layout-center.styl
docs/.vuepress/theme/styles/sidebar.styl

Closes #67
Would appreciate some eyes on this since I had to play around Vuepress' default theme a little bit. I tested on mobile and other browsers.

feat: add nft storage banner

---

code-snippets/quickstart/package-example.json
code-snippets/quickstart/package.json

Closes #59 by replacing Vasco's name as author in package.json with `YOUR NAME`.

Content: Generic author name in package.json examples

---

docs/README.md

Tells users that `status()` exists, and that they can use it.

Adds status() callout.

---

docs/README.md
docs/concepts/content-addressing.md
docs/concepts/decentralized-storage.md
docs/how-tos/query.md
docs/how-tos/retrieve.md
docs/how-tos/store.md
docs/reference/client-library.md

This PR sprinkles gentle reminders throughout the docs that Web3.Storage is free.
Closes #73.

Content: more mentions throughout that Web3.Storage is free

---

docs/.vuepress/theme/layouts/GlobalLayout.vue
docs/.vuepress/theme/styles/theme-dark.styl

fix: footer links colors on dark mode

---

docs/how-tos/query.md
docs/how-tos/retrieve.md
docs/how-tos/store.md

This PR fixes a few broken or otherwise less-useful links in a final pre-launch check.
Ref #69. As the last item in the checklist, this also closes #69.

Fix: pre-launch link check

---

code-snippets/how-to/index.js
code-snippets/how-to/platform-browser.js
code-snippets/how-to/platform-node.js
docs/how-tos/retrieve.md
docs/how-tos/store.md

This is a wip PR to address things that shake out of the how-to testing that @johnnymatthews & @terichadbourne are up to in https://github.com/web3-storage/docs/issues/82. Feel free to push commits here if you see anything with an obvious fix - I'll be tied up for the next few hours but will circle back this afternoon.

fixes for how-to testing feedback

---

docs/community/help-and-support.md

This PR adds a link to Discord on https://docs.web3.storage/community/help-and-support/.
Closes #118.

Content: add Discord link

---

docs/reference/client-library.md

What the title says; gathered descriptions from the src code, let me know if I missed anything.

Add "list()" to JS Client Ref

---

docs/reference/client-library.md

This was renamed recently from "miner".

fix: storage provider address property

---

docs/.vuepress/config.js
docs/how-tos/troubleshooting.md

Closes #153 by creating a troubleshooting page.

Adds troubleshooting to sidebar.

---

code-snippets/how-to/index.js

Per https://github.com/web3-storage/web3.storage/issues/346

fix: snippet store with progress using correct onStoredChunk callback

---

docs/reference/client-library.md

Adds min reqs.

---

docs/README.md

Adds basic link to examples folder.

---

docs/.vuepress/config.js
docs/.vuepress/public/http-api.html
docs/.vuepress/public/schema.yml
docs/reference/client-library.md
package-lock.json

See: https://bafybeie7ay5jhqgbk2j3lrmmh743dyiz7ujzx6mmllc73iilvvyfupvlma.on.fleek.co/http-api.html
Writing much of spec from scratch using https://github.com/web3-storage/web3.storage/blob/main/packages/api/src/index.js as a basis.

HTTP API Reference Docs: ReDoc + schema

---

code-snippets/how-to/dag-cbor.js
code-snippets/how-to/dag-json.js
code-snippets/how-to/package-lock.json
code-snippets/how-to/package.json
docs/.vuepress/config.js
docs/how-tos/store.md
docs/how-tos/work-with-car-files.md
docs/reference/client-library.md

This is a start on the how-to portion of #146.
Leaving as draft until:

How-to store CAR files

---

docs/.vuepress/theme/styles/index.styl

fix: weird background cut off and large bottom page spacing

---

code-snippets/how-to/dag-cbor.js

simpler makeCar function in dag-cbor example

---

.github/workflows/algolia.yml
algolia-config.js
docs/.vuepress/config.js

This PR adds config for Algolia search, pending approval of an open-source plan. **Please don't merge yet.**
Closes https://github.com/web3-storage/docs/issues/62.

feat: add Algolia config

---

docs/how-tos/work-with-car-files.md

update go-carbites example with new API

---

static/schema.yml

Sorry this took so long - I had it gathering dust on my laptop for a while...
Closes #218

chore: add server url to schema.yml

---

docs/.vuepress/config.js
docs/how-tos/pinning-services-api.md
sidebars.js
static/schema.yml

- Added new section How-tos > Pinning services API
- Added pinning API documentation to Reference > HTTP API

feat: add pinning service overview and schema

---

docs/how-tos/troubleshooting.md

Added section on troubleshooting page for slow uploads.

feat: add troubleshooting for slow uploads
