- docs/.vuepress/config.js
- docs/quickstart/README.md
Apparently _quickstart_ is a valid word. So yeah, fixing that.
> 'Quick start' > 'Quickstart'.

- docs/.vuepress/config.js
- docs/.vuepress/theme/styles/code-copy.styl
- docs/.vuepress/theme/styles/index.styl
- package-lock.json
- package.json
This adds `vuepress-plugin-code-copy` to the project, which adds a "copy to clipboard" button to all code blocks. I stole the styles from filecoin-docs (turns out that's where I remember having this feature, not NFT school).
Closes #25
> Add clipboard copy buttons to all code blocks

- docs/.vuepress/config.js
- docs/how-tos/regenerate-api-key.md
- docs/how-tos/regenerate-api-token.md
- docs/how-tos/retrieve.md
- docs/how-tos/store.md
- docs/quickstart/README.md
- docs/reference/client-library.md
This is just a few quick fixes for things @alanshaw called out in our zoom call earlier:
- fixes the `new File([aBlobOrArrayBuffer])` example in storage howto
- imports `File` from the `web3.storage` package instead of `@web-std/file` (node only)
- converts stray `require` statements into `import`s
- replaces "API key" with "API token" to match usage on main site
> Address Alan's feedback from sync call

- docs/how-tos/query.md
- docs/how-tos/store.md
Here's a first pass at the Query how-to. @johndmulhausen how do you feel about the short field descriptions here, with more info in reference? That seems like a better place to describe the `pins` and `deals` objects in detail, IMO.
> Add query how-to

- docs/.vuepress/config.js
- docs/.vuepress/theme/styles/index.styl
- docs/README.md
- package-lock.json
- package.json
This swaps out `vuepress-plugin-element-tabs` for `vuepress-plugin-tabs`, since the former one has a problematic dependency on node-sass that hates newer versions of Node.
As a bonus, the default styles on this one fit into the current theme a bit better:
@johndmulhausen / @johnnymatthews mind trying this out? You'll need to `npm install` after checking out the branch before running.
I tested on my machine with node v14 and v16, and both seemed to work. 🤞
> use different tabs plugin

- docs/README.md
All API tokens now come from `/profile`. The `/tokens` page _will_ exist in the future, but it's gonna be for super fancy token stuff. Most people will just need to use `/profile`.
> Removes /token page reference.

- docs/.vuepress/theme/styles/index.styl
- docs/.vuepress/theme/styles/theme-dark.styl
- docs/README.md
This PR addresses @johnnymatthews' idea from https://github.com/web3-storage/docs/pull/35 by repurposing `<blockquote>` as something more visually similar to a callout. This means we can still use ordinary Markdown syntax without injecting any html.
> Restyle blockquotes as callouts

- docs/.vuepress/theme/styles/index.styl
This was making my eye twitch a little:
I added some css to prevent line wrapping for `code` elements inside a table, to make it look like this:
> prevent code examples in table cells from line wrapping

- docs/.vuepress/config.js
- docs/.vuepress/theme/layouts/404.vue
- docs/.vuepress/theme/styles/header.styl
- docs/.vuepress/theme/styles/theme-dark.styl
Adds top navbar link to main-site About page for consistency. 
_Bonus fix: improves visual styling of 404 page in dark mode._
cc @jnthnvctr
> Add top navbar link to main-site About page

- docs/.vuepress/theme/styles/index.styl
- docs/.vuepress/theme/styles/with-output.styl
This brings in the `with-output` and `output` classes that you can use to tag markdown blocks with for special styling.
It uses the same colors for dark and light mode, but I think they play well against both backgrounds.
Dark mode:
Light mode:
> add with-output and output tags for code blocks

- docs/how-tos/store.md
- docs/reference/client-library.md
This adds an example of using `getFilesFromPath` to the storage how-to for node.js users. 
There's also a bit of noise in the diff where I switched language tags from `js` to `javascript` - I figure we should try to pick one and be consistent, and @johnnymatthews seems to like `javascript` :)
> add section about getFilesFromPath to store howto

- docs/.vuepress/config.js
Otherwise the about page would open on a new tab.
> fix: add target to simulate internal link instead of external

- docs/how-tos/retrieve.md
When https://github.com/web3-storage/web3.storage/pull/165 is merged a new release of the client will happen and you will need to check the `res.ok` property to know if the response was successful. It will not throw.
Apologies for the last minute API change.
> fix: response handling

- docs/how-tos/query.md
This fixes up the truthiness check on the `status` return value in our query how-to as @olizilla suggests in #87.
closes #87.
> clean up truthiness check on status result & tweak language

- docs/README.md
Updates the "Run the Script" section of the quickstart with instructions for uploading multiple files in a single command. Also amends the "Get your file" section slightly for clarity around that.
Closes #60.
> Content: update quickstart "run the script" for multiple files

- docs/how-tos/store.md
This PR adds info to the storage how-to on using the web UI if one doesn't need to do anything dev-ish.
Also clarifies a few other bits of language impacted by the addition.
Closes #21.
> Content: add link to web UI from storage how-to

- docs/how-tos/retrieve.md
This PR changes the following:
- Rearranges retrieval options to put gateway retrieval first, and rearranges the longer sections accordingly
- Minor copy changes in that bulleted list for consistency
- Adds tip in gateway section to include using Web3.Storage Files page
Closes #76.
> Content: Clarify browser retrieval as an option in retrieval how-to

- docs/how-tos/store.md
I added an example to the store how-to that shows how to use the `onRootCid` and `onChunkStored` callbacks.
It's not directly copy/pastable, since it references a `getClient` method that isn't defined anywhere, but hopefully it's obvious how you'd write your own `getClient` function.
closes #61
> add progress callback example to store how-to

- docs/README.md
Closes #74 by adding content in the Quickstart intro that Node isn't your only option.
> Content: indicate in intro that you don't have to use node

- docs/README.md
This PR moves the quickstart prerequisites back into a callout for increased visibility, as spec'd in user testing.
Closes #72.
> Content: put quickstart prereqs in danger box

- code-snippets/quickstart/package-example.json
- code-snippets/quickstart/package-lock.json
- code-snippets/quickstart/package.json
I noticed that the example package.json is requiring a pretty old version of the js client, so this bumps it up to the latest (3.1.0).
> use latest client version in quickstart

- docs/.vuepress/config.js
This WIP PR will edit our footer "Terms of service" link to direct to a header inside the /about page on the main site rather than to an /about page that's going away. (See ongoing thread about the changes [here in Slack](https://protocollabs.slack.com/archives/C02750576C8/p1627516681448400).) 
**DO NOT MERGE** until: 
@jnthnvctr @alanshaw @rafaelramalho19 @olizilla I know this is premature, but please flag us when the changes on your side are done so we can (correct if needed and) get this merged. This needs to be merged pretty immediatly after you make your changes so that we're not directing people to a Terms page that's not there.
> MERGE BLOCKED: update footer link

- code-snippets/quickstart/put-files.js
This PR refactors put files to do the following things:
1. Collect _all_ the files from _all_ the given paths and _then_ upload them all into the same directory, rather than getting a CID per path.
2. Return on failure when there are no files (I know technically we didn't need to do this _before_, but leaving it to fall through makes it brittle to changes and we actually _need_ to do this now to prevent an error being thrown)
3. Consistently use 2 spaces for indentation. The current file is a mixture of 2 and 4 spaces. The JS community traditionally use 2 spaces so that's what I went with here. Sorry for the noise.
I don't know if (1) was the original intention or not, but I've just had a user asking about why the files don't all get put in one directory. I _think_ this is what I'd expect …
> refactor: quickstart put-files.js

- docs/README.md
This adds a tip box to the quickstart to explain that you can upload a directory or pass in multiple files to the example script. 
@atopal it sounds like a few people wanted to see an example of uploading a bunch of files at once (e.g. #124). 
I didn't add a full code example since the rest of the text talks about "your file" in the singular. Do you think this callout is enough?
> quickstart: callout that you can add multiple files / directories

- code-snippets/how-to/example-listing-upload.json
- code-snippets/how-to/index.js
- docs/.vuepress/config.js
- docs/how-tos/list.md
This add a how-to guide for listing your uploads using the JS client, with a mention that you can just view things on the files page as well.
closes #112
> content: add list how-to guide

- docs/reference/client-library.md
I was digging through the new issues and impulsively grabbed this one :) Hopefully the examples make it clear why you'd want to override the default. The example CIDs are valid in case anyone decides to look them up :)
closes #125
> document wrapFilesWithDirectory option

- docs/.vuepress/theme/components/Page.vue
- docs/.vuepress/theme/layouts/GlobalLayout.vue
This PR slightly increases min-height of `#global-layout` so the footer nav doesn't run short of the bottom of the page on low-content pages.
This had originally been fixed in https://github.com/web3-storage/docs/pull/19/files but I believe that adding the NFT Storage banner re-introduced the problem. @terichadbourne - can you think of a more elegant solution than this one? It feels a bit hacky, but it works.
Closes https://github.com/web3-storage/docs/issues/129.
> Style: Banner at bottom on short pages

- docs/how-tos/store.md
Previous PR only changed the snippet. I was now checking if the deploy worked and noticed that the docs content also had the wrong naming
> fix: showing progress docs also need on stored chunk

- docs/reference/client-library.md
Based on https://github.com/web3-storage/web3.storage/pull/293
Pretty straightforward stuff given similarities to `put()`, but as you can see there are fewer parameters exposed in the `{options}` object.
> putCar() docs for JS client reference

- code-snippets/how-to/dag-cbor.js
- code-snippets/how-to/package-lock.json
- code-snippets/how-to/package.json
- docs/how-tos/work-with-car-files.md
@alanshaw inspired me to add some more interesting examples of using `dag-cbor` in the "working with CARs" guide.
This adds an example of linking from CBOR to CBOR, and from CBOR to UnixFS. 
Everything seems to work... I added `"type": "module"` to the package.json for the example code, so it's easier to try it out now. Just `cd code-snippets/how-tos && node dag-cbor.js`.
Oddly none of the cbor CIDs I put will resolve in the [IPLD explorer](https://explore.ipld.io). E.g. if I paste in `bafyreid7hvce4pzcy56s4hwu7xrt3dnnzzfvilzfwsadvf6q4eqild6ndy` it just spins forever. The gateway is able to traverse to the linked file though: https://bafyreid7hvce4pzcy56s4hwu7xrt3dnnzzfvilzfwsadvf6q4eqild6ndy.ipfs.dweb.link/file
> Add dag-cbor examples with IPLD links

- docs/how-tos/retrieve.md
- docs/how-tos/troubleshooting.md
This adds a bit to the retrieval guide about controlling the default filename for downloads when using gateway links. I also added a new troubleshooting entry that links to the new section.
closes #154
> explain how to control filename of gateway downloads

- docs/.vuepress/config.js
- docs/reference/client-library.md
- docs/reference/js-utilities.md
This adds a new reference page for the js utility libraries `files-from-path` and `ipfs-car`. The new page just gives a little overview of each and links to the readme, etc.
Closes #128
> add reference page for js util libs

- docs/.vuepress/config.js
> fix: match nav links order to match main website

- docs/.vuepress/config.js
- docs/how-tos/list-directory-contents.md
This adds a how-to guide for listing the contents of an IPFS directory without downloading it, using either `ipfs-http-client` or raw HTTP requests to a remote node (e.g. dweb.link), plus an `ipfs ls` cli example.
Closes https://github.com/web3-storage/web3.storage/issues/340
> add how-to for listing directory contents

- docs/how-tos/work-with-car-files.md
This adds a section to the "working with CARs" How-To about splitting large cars into chunks that will fit under the 100 MB limit in the HTTP API. It has examples using `carbites-cli`, plus the `carbites` js library and `go-carbites` Go module.
Closes #175
> feat: add section on CAR splitting to CAR how-to

- src/plugin/index.js
- src/util/countly.js
This changes the way we load the countly SDK.
Quick recap of how the countly integration works, since I don't think it's documented well elsewhere. 
Basically, to hook into docusaurus's router and get notified on route changes, I had to write a custom docusaurus plugin and use the `onRouteUpdate` hook (described in this [SO answer](https://stackoverflow.com/a/63981821/1292992)). Unfortunately, it seems this hook doesn't fire for the initial page load.
This changes the plugin to initialize the countly sdk in a script tag that gets injected into every page - because this script executes at the global scope and can't `import` stuff from the bundle, it loads the countly SDK from a CDN into the global `window.Countly` object instead of importing the npm package.
I tested locally with …
> fix: init countly at page load & track initial pageview

- docs/how-tos/work-with-car-files.md
Just realized that we're linking to `nodejs.com` instead of `nodejs.org` in this file.
> fix: update broken links to nodejs.org

- docs/reference/js-client-library.md
Looks like the backtics were confusing the markdown parser for the tab plugin.
closes #211
> fix: broken tab headers in js client reference

- docs/how-tos/troubleshooting.md
- static/schema.yml
This adds a note about rate limits to the HTTP api spec and an entry to the troubleshooting section.
closes https://github.com/web3-storage/web3.storage/issues/269
> chore: add info about rate limits to http docs & troubleshooting
